import React from 'react';
import { Database, Map, Lightbulb } from 'lucide-react';

export const ProjectInsights: React.FC = () => {
  return (
    <div className="mb-10">
      <div className="flex items-center justify-between mb-6">
        <h2 className="text-2xl font-bold text-slate-200">Project Presentation & Analysis</h2>
      </div>
      
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        
        {/* Architecture Card */}
        <div className="bg-slate-800/40 backdrop-blur-xl rounded-2xl p-6 border border-slate-700/50 hover:border-slate-600/50 hover:-translate-y-1 transition-all duration-300">
          <div className="flex items-center gap-4 mb-4">
            <div className="p-3 bg-blue-500/20 rounded-xl">
              <Database className="w-6 h-6 text-blue-400" />
            </div>
            <h3 className="text-lg font-semibold text-white">Digital Twin Architecture</h3>
          </div>
          <p className="text-slate-400 text-sm leading-relaxed">
            This dashboard is the visual frontend of a robust Big Data pipeline. Real-time telemetry is generated by a Python simulator, buffered through <span className="text-blue-300 font-medium">Apache Kafka</span> for high-throughput ingestion, and stored in <span className="text-green-300 font-medium">MongoDB</span>. A distributed <span className="text-orange-300 font-medium">Apache Spark</span> engine runs periodic batch jobs to distill thousands of raw readings into actionable intelligence.
          </p>
        </div>

        {/* City Simulation Card */}
        <div className="bg-slate-800/40 backdrop-blur-xl rounded-2xl p-6 border border-slate-700/50 hover:border-slate-600/50 hover:-translate-y-1 transition-all duration-300">
          <div className="flex items-center gap-4 mb-4">
            <div className="p-3 bg-emerald-500/20 rounded-xl">
              <Map className="w-6 h-6 text-emerald-400" />
            </div>
            <h3 className="text-lg font-semibold text-white">City Simulation Model</h3>
          </div>
          <p className="text-slate-400 text-sm leading-relaxed">
            The simulated city is divided into 5 distinct zones with unique statistical profiles. For example, the <span className="text-slate-200 font-medium">Downtown</span> zone experiences extreme traffic congestion, while the <span className="text-slate-200 font-medium">West</span> zone simulates an industrial area with consistently poorer Air Quality (AQI). The simulation also includes a mathematical wave to mimic daily 'rush hour' cycles.
          </p>
        </div>

        {/* Driving Solutions Card */}
        <div className="bg-slate-800/40 backdrop-blur-xl rounded-2xl p-6 border border-slate-700/50 hover:border-slate-600/50 hover:-translate-y-1 transition-all duration-300">
          <div className="flex items-center gap-4 mb-4">
            <div className="p-3 bg-purple-500/20 rounded-xl">
              <Lightbulb className="w-6 h-6 text-purple-400" />
            </div>
            <h3 className="text-lg font-semibold text-white">Driving Smart Solutions</h3>
          </div>
          <div className="text-slate-400 text-sm leading-relaxed space-y-2">
            <p>By correlating this data, city planners can drive automated solutions:</p>
            <ul className="list-disc pl-5 space-y-1">
              <li><strong className="text-slate-300">Traffic vs. AQI:</strong> If severe traffic in Downtown causes AQI spikes, trigger automated rerouting of heavy vehicles.</li>
              <li><strong className="text-slate-300">Heat Islands:</strong> Identify persistent temperature spikes in the South to deploy cooling centers.</li>
              <li><strong className="text-slate-300">Predictive Alerts:</strong> Warn citizens of impending poor air quality days in advance.</li>
            </ul>
          </div>
        </div>

      </div>
    </div>
  );
};
